spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/minha_base_prod
    username: postgres
    password: senha_prod
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
